// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-mmEUhHrVyhriGN3MHmqaKVdfsb8R5I',
    appId: '1:333363314070:web:b94694446d7e67298571b7',
    messagingSenderId: '333363314070',
    projectId: 'imagestore-2522b',
    authDomain: 'imagestore-2522b.firebaseapp.com',
    storageBucket: 'imagestore-2522b.appspot.com',
    measurementId: 'G-WRHK7SN46R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBHrVbTJ8iGPGMf7jcYpoMvlIiJY-997E',
    appId: '1:333363314070:android:a60ee734197f7c248571b7',
    messagingSenderId: '333363314070',
    projectId: 'imagestore-2522b',
    storageBucket: 'imagestore-2522b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHnyNQ8hVHjoxH3ZPXNcXifrGZ5tNzXWo',
    appId: '1:333363314070:ios:60903865709aa9138571b7',
    messagingSenderId: '333363314070',
    projectId: 'imagestore-2522b',
    storageBucket: 'imagestore-2522b.appspot.com',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHnyNQ8hVHjoxH3ZPXNcXifrGZ5tNzXWo',
    appId: '1:333363314070:ios:cbb0817411d00aa98571b7',
    messagingSenderId: '333363314070',
    projectId: 'imagestore-2522b',
    storageBucket: 'imagestore-2522b.appspot.com',
    iosBundleId: 'com.example.skincareApp.RunnerTests',
  );
}
